# -*- mode: ruby -*-
# vi: set ft=ruby :

# The script makes sure that SSH is enabled on the machine.
$script = <<SCRIPT
echo I am provisioning...
ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $script
end
