# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1604"

  config.ssh.insert_key = false

  config.vm.provision "docker" do |d|
    d.pull_images "ros:kinetic"
  end
end
