# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  # config.ssh.private_key_path = "~/.ssh/id_rsa"
  # config.ssh.insert_key = true

  config.vm.provision "docker",
    images: ["ros:kinetic"]

end
